[package]
name = "asampo-gtk"
version = "0.0.0"
edition = "2021"

[dependencies]
gtk = { package = "gtk4", version = "0.8.1", features = ["v4_12"] }
libasampo = { git = "https://github.com/mkforsb/libasampo" }
audiothread = { git = "https://github.com/mkforsb/libasampo" }
env_logger = "0.11.3"
uuid = { version = "1.8.0", features = ["v4"] }
indoc = "2.0.5"
log = "0.4.21"
anyhow = "1.0.82"

[build-dependencies]
glib-build-tools = "0.19.0"
