// MIT License
//
// Copyright (c) 2024 Mikael Forsberg (github.com/mkforsb)

use std::rc::Rc;

use gtk::gdk::ModifierType;
use libasampo::{samples::Sample, samplesets::DrumkitLabel, sequences::DrumkitSequenceEvent};
use uuid::Uuid;

use crate::view::dialogs::{self, InputDialogContext, SelectFolderDialogContext};

#[derive(Debug, Clone)]
pub enum AppMessage {
    NoOp,
    Sequence(Vec<AppMessage>),
    LogError(Rc<anyhow::Error>), // uses `Rc` for `derive Clone`
    DialogClosed,
    TimerTick,
    SettingsOutputSampleRateChanged(String),
    SettingsBufferSizeChanged(u16),
    SettingsSampleRateConversionQualityChanged(String),
    SettingsSamplePlaybackBehaviorChanged(String),
    SettingsSaveOnQuitBehaviorChanged(String),
    SettingsSaveChangedSequenceBehaviorChanged(String),
    SettingsSaveChangedSampleSetBehaviorChanged(String),
    SettingsSynchronizeChangedSampleSetBehaviorChanged(String),
    AddFilesystemSourceNameChanged(String),
    AddFilesystemSourcePathChanged(String),
    AddFilesystemSourcePathBrowseClicked,
    AddFilesystemSourcePathBrowseSubmitted(String),
    AddFilesystemSourceExtensionsChanged(String),
    AddFilesystemSourceClicked,
    SampleListSampleSelected(u32),
    SampleSetSampleSelected(Sample),
    SamplesFilterChanged(String),
    SampleSidebarAddToSetClicked,
    DeleteSampleFromSetClicked(Sample, Uuid),
    SampleSidebarAddToMostRecentlyUsedSetClicked,
    SourceEnabled(Uuid),
    SourceDisabled(Uuid),
    SourceDeleteClicked(Uuid),
    SourceLoadingMessage(Uuid, Vec<Result<Sample, libasampo::errors::Error>>),
    SourceLoadingDisconnected(Uuid),
    LoadSavefileRequested(String),
    SaveBeforeLoadConfirmDialogOpened,
    SaveBeforeLoadPerformSave,
    SaveBeforeLoadSaveDialogOpened,
    SaveBeforeLoadPerformLoad,
    LoadFromSavefile(String),
    SaveToSavefile(String),
    AddSampleSetClicked,
    InputDialogOpened(InputDialogContext),
    InputDialogSubmitted(InputDialogContext, String),
    InputDialogCanceled(InputDialogContext),
    SelectFolderDialogOpened(SelectFolderDialogContext),
    SampleSetSelected(Uuid),
    SampleSetDeleteClicked(Uuid),
    SampleSetDeleteDialogOpened,
    SampleSetDeleteConfirmed,
    SampleSetDeleteCanceled,
    SampleSetSampleLabelChanged(Sample, Option<DrumkitLabel>),
    SampleSetDetailsLoadInDrumMachineClicked,
    SampleSetDetailsExportClicked,
    ExportDialogOpened(dialogs::ExportDialogView),
    ExportDialogClosed,
    ExportTargetDirectoryChanged(String),
    ExportTargetDirectoryBrowseClicked,
    ExportTargetDirectoryBrowseSubmitted(String),
    PerformExportClicked,
    PlainCopyExportSelected,
    ConversionExportSelected,
    ExportJobMessage(libasampo::samplesets::export::ExportJobMessage),
    ExportJobDisconnected,
    StopAllSoundButtonClicked,
    DrumMachineTempoChanged(u16),
    DrumMachineSwingChanged(u32),
    DrumMachinePlayClicked,
    DrumMachineStopClicked,
    DrumMachineBackClicked,
    DrumMachineSaveSequenceClicked,
    DrumMachineSaveSequenceAsClicked,
    DrumMachineClearSequenceClicked,
    DrumMachineSaveSampleSetClicked,
    DrumMachineSaveSampleSetAsClicked,
    DrumMachineClearSampleSetClicked,
    DrumMachinePadClicked(usize),
    DrumMachinePartClicked(usize, ModifierType),
    DrumMachineStepClicked(usize),
    DrumMachinePlaybackEvent(DrumkitSequenceEvent),
    AssignSampleToPadClicked(usize),
    SequenceSelected(Uuid),
    AddSequenceClicked,
    SequenceDeleteClicked(Uuid),
    SequenceDeleteDialogOpened,
    SequenceDeleteConfirmed,
    SequenceDeleteCanceled,
    LoadSequenceConfirmSaveDialogOpened,
    LoadSequenceConfirmSaveChanges,
    LoadSequenceConfirmDiscardChanges,
    LoadSequenceCancelSave,
    LoadSequenceConfirmAbandonDialogOpened,
    LoadSequenceConfirmAbandon,
    LoadSequenceCancelAbandon,
    ClearSequenceConfirmDialogOpened,
    ClearSequenceConfirm,
    ClearSampleSetConfirmDialogOpened,
    ClearSampleSetConfirm,
    LoadSampleSetConfirmSaveDialogOpened,
    LoadSampleSetConfirmSaveChanges,
    LoadSampleSetConfirmDiscardChanges,
    LoadSampleSetConfirmAbandonDialogOpened,
    LoadSampleSetConfirmAbandon,
    SynchronizeSampleSetDialogOpened,
    SynchronizeSampleSetConfirm,
    SynchronizeSampleSetUnlink,
    SynchronizeSampleSetCancel,
    QuitRequested,
    SaveBeforeQuitConfirmDialogOpened,
    SaveBeforeQuitSaveDialogOpened,
    Quit,
    SaveAndQuitBegin,
    SaveAndQuitFinish(String),
}
