name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: deps
      run: sudo apt install -y --no-install-recommends libgtk-4-dev libpulse-dev 
    - name: rustfmt
      run: cargo fmt --all --check
    - name: clippy
      run: cargo clippy --all-targets -- -Dwarnings
    - name: build
      run: cargo build --verbose
    - name: test
      run: cargo test --verbose
